### PR TITLE
Hacktoberfest: Updated readme to make it more attractive and understandable

### PR DESCRIPTION
**Pull request by negativenagesh**
@adityajn105 please consider my effort and would be helpful if you add hacktoberfest-approved or something and merge this PR

## Updated README.md to include:

- Overview of the MLfromScratch library
- Detailed descriptions of modules and algorithms
- Added Dimensionality Reduction section with PCA explanation
- Enhanced formatting for clarity and organization

### CODE REVIEW

**Review by adityajn105 — APPROVED** [review]
Hi Subrahmanya, thanks for your contribution. I love your enthusiasm, keep it up and it will take you to places. I am approving your PR. Enjoy the hacktoberfest. 🙂

**Comment by negativenagesh** [comment]
@adityajn105 ... Thank you so much 😀

I think you have to give hacktoberfest-approved label or something right?, or else it won't be considered isn't it? I'm asking I don't know exactly.. I'm new to open source.. I have tried so many times reaching you through your mails, linkedin, instagram. you are not so active on github isn't it? 

image


## Please Review all my PRs, that would be so helpful and kind of you

**Comment by adityajn105** [comment]
Can you check now, if it shows accepted?

**Comment by negativenagesh** [comment]
@adityajn105 
I think you have to manually add the label hacktoberfest -accepted label to it like this one below

**Comment by adityajn105** [comment]
@negativenagesh Please check now. I added label to repository.

**Comment by negativenagesh** [comment]
> @negativenagesh Please check now. I added label to repository.

@adityajn105 sorry for bothering you..

You have to add it to This PR or my above first comment not to the repository

**Comment by negativenagesh** [comment]
@adityajn105 

# you have to add the label "hacktoberfest-accepted" like this

https://github.com/gunjjoshi/csy-final-website/pull/4

image

**Pull request merged**
